### ISSUE TITLE
Hi! Do you have an official code? 

### ISSUE THREAD

**Issue by weihongwei3** [skmatz/prcc-pytorch#1]
If so, can you share it? thanks

**Comment by 5n7-sk** [comment]
@weihongwei3

Sorry.
I'm not official and I don't have the code.
I was going to implement it to do my research related to PRCC, but I don't think I can implement or publish it yet because I may not be able to continue my research due to the recent privacy issues.

**Comment by weihongwei3** [comment]
> @weihongwei3
> 
> Sorry.
> I'm not official and I don't have the code.
> I was going to implement it to do my research related to PRCC, but I don't think I can implement or publish it yet because I may not be able to continue my research due to the recent privacy issues.

Thank you for your reply. It doesn't matter. I am also trying. I heard that the structure of the PCB code can be used to assist in the implement, which may be helpful to you.
